### ISSUE TITLE
[POST] API/dispositivos

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Jingle#11]
Al intentar dar de alta algun dispositivo siempre regresa el error "02" no importa cual sea el nombre que le de al dispositivo. 

Ejemplos de nombres que intente usar:
GerardoDispositivo
Gerardo1234
asdadafgfGera
dafgikskd

**Comment by Yayo-Arellano** [comment]
Hice unas pruebas y pude registar el dispositivo la primera vez. Despues cerre la sesion y cuando volvi a entrar en la parte de (API/usuarios/login) me regreso el "04" diciendo que el dispositivo no se habia dado de alta todavia.

Despues intente dar de alta otra vez el dipositivo (API/dispositivos) y me regresaba el error "02"

Al parecer en query si existe el nombre o el devideID y como si existe el deviceID regresa el error 02

<code>
$query = "SELECT IF(COUNT(*) > 0, 1, 0) AS existe FROM dispositivo WHERE cuentaID = $this->cuentaID AND (nombre = '$nombre' OR deviceID = '$deviceID')";
</code>

El problema ahora es en API/usuarios/login que no deberia regresar 04 porque ese dispositivo ya se dio de alta.

**Comment by Yozki** [comment]
Tenias razón, ese método estaba mal, no tenia la variable $deviceID entre comillas como deben ser los strings por lo que fallaba la query.

Prueba ahora porfa.

**Comment by Yayo-Arellano** [comment]
Ya se corrigio
