### ISSUE TITLE
[POST] API/coordenadas

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Jingle#12]
Puedes revisar esta webApi, me regresa siempre status code 401. 

Estoy usando este usuario
usuario: gerardo_28@hotmail.com
pass: asdfg

Y le envio la coordenadas
lat
lng

**Comment by Yozki** [comment]
Modifiqué el [método](https://github.com/NopalDesignAndSoftware/Jingle/wiki/API#post-apicoordenadas)

**Comment by Yayo-Arellano** [comment]
Parece que ya se estan registrando las coordenadas. Voy a cerrar el issue si existe algun problema despues lo vuelvo abrir
