### ISSUE TITLE
[GET] API/coordenadas

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Jingle#13]
La funcion regresa.

[{"deviceID":null,"deviceModel":null,"deviceOS":null,"nombre":null,"coordenadas":null}]

Despues de haber dado de alta un dispositivo y haber enviado coordenadas por el metodo [POST] API/coordenadas.

**Comment by Yozki** [comment]
Listo, revisa porfa! [API/coordenadas/{deviceID}](https://github.com/NopalDesignAndSoftware/Jingle/wiki/API#get-apicoordenadas)

**Comment by Yayo-Arellano** [comment]
Estoy batallando con este metodo ya intente de varias formas y siempre regresa el error "05"

Usando el metodo GET.
BasicAuth : gerardo_28@hotmail.com:asdfg

http://jingle.nop.al/API/coordenadas/ed297ae3f59a085f?deviceID=ed297ae3f59a085f

Tambien hice pruebas con:
http://jingle.nop.al/API/coordenadas?deviceID=ed297ae3f59a085f
http://jingle.nop.al/API/coordenadas/ed297ae3f59a085f

**Comment by Yozki** [comment]
Listo.

**Comment by Yayo-Arellano** [comment]
La actualizacion si corrigio el problema del error "05" pero aun existe otro problema.
El servidor deberia regresar las coordenadas de todos los dispositivos que esten registrados con la cuenta en especifico.

Lo que regresa ahorita el JSON es: 
El codigo, un dispositivo (en esta caso "coordenadas") y dentro de este esta un arreglo que contiene las coordenadas (tambien se llama "coordenadas").
```
{
    "codigo": "00",
    "coordenadas": {
        "deviceID": "ed297ae3f59a085f",
        "deviceModel": "samsung GT-I9190",
        "deviceOS": "18",
        "nombre": "YayoS4mini",
        "coordenadas": [
        ]
    }
}
```

Un ejemplo de lo que deberia regresar el servidor es:

Contiene un arreglo de "dispositivos" en este caso DISPOSITIVO PRUEBA 1, DISPOSITIVO PRUEBA 2 y DISPOSITIVO PRUEBA 3. 
Cada dispositivo tiene sus coordeandas, en el caso de DISPOSITIVO PRUEBA 2 este no tiene coordenadas dadas de alta todavia.

INFO: tambien agrega por favor el codigo del color para dibujar la ruta con el color que se hubiera dado de alta.
```
{
    "codigo": "00",
    "dispositivos": [
        {
            "deviceID": "DISPOSITIVO PRUEBA 1",
            "deviceModel": "DISPOSITIVO PRUEBA 1",
            "deviceOS": "DISPOSITIVO PRUEBA 1",
            "nombre": "DISPOSITIVO PRUEBA 1",
            "colorCode": "Rojo",
            "coordenadas": [
                {
                    "fecha": "string",
                    "lat": "double",
                    "lng": "double"
                },
                {
                    "fecha": "string",
                    "lat": "double",
                    "lng": "double"
                },
                {
                    "fecha": "string",
                    "lat": "double",
                    "lng": "double"
                }
            ]
        },
        {
            "deviceID": "DISPOSITIVO PRUEBA 2",
            "deviceModel": "DISPOSITIVO PRUEBA 2",
            "deviceOS": "DISPOSITIVO PRUEBA 2",
            "nombre": "DISPOSITIVO PRUEBA 2",
            "colorCode": "Azul",
            "coordenadas": []
        },
        {
            "deviceID": "DISPOSITIVO PRUEBA 3",
            "deviceModel": "DISPOSITIVO PRUEBA 3",
            "deviceOS": "DISPOSITIVO PRUEBA 3",
            "nombre": "DISPOSITIVO PRUEBA 3",
            "colorCode": "Amarillo",
            "coordenadas": [
                {
                    "fecha": "string",
                    "lat": "double",
                    "lng": "double"
                }
            ]
        }
    ]
}
```

**Comment by Yozki** [comment]
https://github.com/NopalDesignAndSoftware/Jingle/wiki/API#get-apicoordenadas

**Comment by Yayo-Arellano** [comment]
La app sigue regresando 

```{
    "codigo": "00",
    "coordenadas": {
        "deviceID": "ed297ae3f59a085f",
        "deviceModel": "samsung GT-I9190",
        "deviceOS": "18",
        "nombre": "YayoS4mini",
        "coordenadas": [
        ]
    }
}```

**Comment by Yozki** [comment]
Asi es por diseño, cuando el método recibe un deviceID va a regresar ese formato, cuando NO le envias deviceID recibe el formato de arriba.

Es contra-intuitivo que si solo va a regresar la información de 1 solo dispositivo lo meta en un arreglo llamado "Dispositivos".   

Como vez pordrás usarlo asi? O de plano necesitas que tengan el mismo formato?

[GET] API/coordenadas
[GET] API/coordenadas/xxxxxxxx

Yo supuse que se utilizan en casos de uso diferentes y por eso no me forzé a usar el mismo formato, pero tu dime.

**Comment by Yayo-Arellano** [comment]
Este error ya quedo asi dejalo como esta. Lo voy a cerrar.
