### ISSUE TITLE
Dar de alta dispositivo

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Jingle#3]
Se necesita un servicio web que se llama despues de iniciar sesion por primera vez poder de alta el dispositivo asi como otros datos.
Los datos que se quieren dar de alta serian:
Nombre, Tipo de cuenta (master o junior), OS del dispositivo (Android 4.0, Android 4.2, etc).
El servicio podria quedar:
RECIBE:
basicAuth
nombre: <b>String</b> 
tipoCuenta: <b>String</b>  (Tal vez aqui se pueda manejar como boleano ex: isMaster? T or F)
OS: <b>String</b>  

Respuesta:
isOK: <b>bool</b>  (Verdadero en caso de ser exitoso, false en caso de que exista un error ex: que se quiera dar de alta el mismo nombre)

**Comment by Yozki** [comment]
https://github.com/NopalDesignAndSoftware/Jingle/issues/3

Me dices si necesita algun cambio.
