### ISSUE TITLE
API/coordenadas:Necesita regresar mas informacion.

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Jingle#4]
El webApi actual regresa solamente informacion de las coordenada y la fecha pero no permite saber de que dispositivos son estas posiciones. 
Esta informacion es necesaria para que al momento de mostrar en el mapa los marcadores estos muestran la informacion indicando desde que dipositivo se enviaron.
El WebApi podria quedar asi:

Recibe:
basicAuth

Responde:
<code>[
    {
        "nombre": "string",
        "coordenadas": [
            {
                "fecha": "dateTime",
                "lat": "double",
                "lon": "double"
            },
            {
                "fecha": "dateTime",
                "lat": "double",
                "lon": "double"
            }
        ]
    },
    {
        "nombre": "string",
        "coordenadas": [
            {
                "fecha": "dateTime",
                "lat": "double",
                "lon": "double"
            },
            {
                "fecha": "dateTime",
                "lat": "double",
                "lon": "double"
            }
        ]
    }
]
</code>

Ejemplo:
<code>  
[
  {
        "nombre": "Dispositivo1",
        "coordenadas": [
            {
                "fecha": "2038-01-19 03:14:07",
                "lat": "123.12323123",
                "lon": "123.1323213123"
            },
            {
                "fecha": "2038-01-19 03:12:07",
                "lat": "123.12323123",
                "lon": "123.1323213123"
            },
        ]
    },
    {
        "nombre": "Dispositivo Gerardo",
        "coordenadas": [
           {
                "fecha": "2038-01-19 03:14:07",
                "lat": "13.134464435",
                "lon": "212.6342423"
            },
           {
                "fecha": "2038-01-19 03:12:07",
                "lat": "12313.56768768",
                "lon": "123.54564564"
            }
        ]
    }
]
</code>

**Comment by Yayo-Arellano** [comment]
@Yozki  Si tienes dudas me avisas

**Comment by Yozki** [comment]
Listo, actualizé la [Wiki](https://github.com/NopalDesignAndSoftware/Jingle/wiki/API#get-apicoordenadas)
