### ISSUE TITLE
Error [POST] /usuarios/login

### ISSUE THREAD

**Issue by Yozki** [NopalDesignAndSoftware/Jingle#8]
"LA app ya permite iniciar sesion con el E-mail pero no importa que valor ponga en la contraseña siempre regresa el codigo 04.

El codigo 04 indica que el usuario y la contraseña son correctos y que el dispositivo desde el que se intento iniciar sesion no se ha dado de alta.

Cuando el usuario y la contraseña no conciden utilizamos el codigo 03.

UPDATE:
No importa que en correo ponga cualquier cosa y en el password cualquier cosa para que regrese 04.
EX:
basicAuth asdasd:asdadasd
Y el servicio regresa 04"

**Comment by Yozki** [comment]
Listo, se puede probar en /tests.html.

**Comment by Yayo-Arellano** [comment]
Necesito un usuario para poder probar.
