### ISSUE TITLE
[Post] API/cuentas

### ISSUE THREAD

**Issue by Yayo-Arellano** [NopalDesignAndSoftware/Jingle#9]
Siempre que quiero crear un usuario me regresa el error 01 indicando que ya existe es correo electronico.

Ejemplo: 
E-mail: asdadafksk@hotmail.com

**Comment by Yozki** [comment]
Pues ya me está funcionando pero no cambié nada, se me hace raro, prueba porfa.
https://github.com/NopalDesignAndSoftware/Jingle/wiki/API#post-apicuentas

**Comment by Yayo-Arellano** [comment]
El error estaba de mi lado
